host:
    replica_id: 3
    raft_address: "mb3:21513"
    wal_dir: "/data"
    nodehost_dir: "/data"
    deployment_id: 0
    peer: 
        1: "mb1:21511"
        2: "mb2:21512"
        3: "mb3:21513"
    clickhouse:
        address: "clickhouse-mb3:9000"
replica:
    1:
        bootstrap: false
        id: "topic-a"
        alias: "Topic A"
        type: "message-broker"
        config: |
            {
                "exit_message": "server 3, is closed. ðŸ”‹"
            }
    2:
        bootstrap: false
        id: "ondisk-fsm-poc"
        alias: "Happy"
        type: "happy"
        config: |
            {
                "exit_message": "server 3, is closed. ðŸ”‹",
                "clickhouse_addr": "clickhouse-mb3:9000"
            }
    3:
        bootstrap: false
        id: "lease"
        alias: "lease"
        type: "lease"
        config: |
            {}
