host:
    replica_id: 1
    raft_address: "mb1:21511"
    wal_dir: "/data"
    nodehost_dir: "/data"
    deployment_id: 0
    peer: 
        1: "mb1:21511"
        2: "mb2:21512"
        3: "mb3:21513"
replica:
    1:
        bootstrap: true
        id: "topic-a"
        alias: "Topic A"
        type: "message-broker"
        config: |
            {
                "exit_message": "server 1! is closed, bye byee ğŸ«°ğŸ½ğŸ’• see u ğŸ¥¹"
            }
    2:
        bootstrap: true
        id: "ondisk-fsm-poc"
        alias: "Happy"
        type: "happy"
        config: |
            {
                "exit_message": "server 1! is closed, bye byee ğŸ«°ğŸ½ğŸ’• see u ğŸ¥¹",
                "clickhouse_addr": "clickhouse-mb1:9000"
            }
