name: Build and upload user-profile example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Hello"
        required: true
        default: "staging"
  push:
    branches:
      - main

jobs:
  send-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:desain-gratis-ci

      - name: Send deploy metadata
        uses: desain-gratis/deployd-gh-action@v1
        with:
          url: http://mb1:9999
          namespace: desain-gratis
          name: user-profile
          build-script: ./example/user-profile/build.sh
          archive: ./example/user-profile/dist
